"""Author a coarse collision-only object in the external Sponza .blend.

Run with Blender:
    blender -b /path/to/sponza.blend \
        --python tools/ceasset/author_sponza_collision.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import bpy


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "ceasset"))
sys.path.insert(0, str(ROOT / "tools" / "blender_addon"))
for module_name in tuple(sys.modules):
    if module_name == "ceassetlib" or \
            module_name.startswith("ceassetlib.") or \
            module_name == "cengine_asset_exporter" or \
            module_name.startswith("cengine_asset_exporter."):
        del sys.modules[module_name]

from cengine_asset_exporter.exporter import (  # noqa: E402
    asset_path_for_project,
    source_fingerprint,
)
from cengine_asset_exporter.physics import write_physics_asset  # noqa: E402


SOURCE_NAME = "sponza"
COLLISION_NAME = "SponzaCollision"
DECIMATE_RATIO = 0.08
STRUCTURAL_MATERIALS = {
    "arch",
    "bricks",
    "ceiling",
    "column_a",
    "column_b",
    "column_c",
    "details",
    "roof",
}
FLOOR_MATERIALS = {"floor"}


def _remove_previous() -> None:
    """Remove only the collision object generated by this script."""
    previous = bpy.data.objects.get(COLLISION_NAME)
    if previous is None:
        return
    mesh = previous.data if previous.type == "MESH" else None
    bpy.data.objects.remove(previous, do_unlink=True)
    if mesh is not None and mesh.users == 0:
        bpy.data.meshes.remove(mesh)


def _mesh_object(
    source: bpy.types.Object,
    name: str,
    materials: set[str],
) -> bpy.types.Object:
    """Copy selected material sections into a new mesh object."""
    selected_material_indices = {
        index for index, slot in enumerate(source.material_slots)
        if slot.name in materials
    }
    polygons = [
        polygon for polygon in source.data.polygons
        if polygon.material_index in selected_material_indices
    ]
    if not polygons:
        raise RuntimeError(f"{name} has no selected Sponza polygons")
    used_vertices = sorted({
        vertex_index
        for polygon in polygons
        for vertex_index in polygon.vertices
    })
    remap = {
        source_index: target_index
        for target_index, source_index in enumerate(used_vertices)
    }
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(
        [
            source.matrix_world @ source.data.vertices[index].co
            for index in used_vertices
        ],
        [],
        [
            [remap[index] for index in polygon.vertices]
            for polygon in polygons
        ],
    )
    mesh.update()
    result = bpy.data.objects.new(name, mesh)
    source.users_collection[0].objects.link(result)
    return result


def main() -> None:
    """Create, simplify, tag, and save Sponza collision authoring."""
    source = bpy.data.objects.get(SOURCE_NAME)
    if source is None or source.type != "MESH":
        raise RuntimeError("sponza.blend has no mesh object named sponza")
    spawn = next((
        obj for obj in bpy.context.scene.objects
        if obj.get("ce_classname", "") == "player_spawn"
    ), None)
    if spawn is None:
        raise RuntimeError("sponza.blend has no player_spawn entity")

    _remove_previous()
    collision = _mesh_object(
        source, COLLISION_NAME, STRUCTURAL_MATERIALS)
    floor = _mesh_object(
        source, f"{COLLISION_NAME}_Floor", FLOOR_MATERIALS)

    bpy.context.view_layer.objects.active = collision
    collision.select_set(True)
    modifier = collision.modifiers.new(
        "CoarseCollision", type="DECIMATE")
    modifier.decimate_type = "COLLAPSE"
    modifier.ratio = DECIMATE_RATIO
    modifier.use_collapse_triangulate = True
    bpy.ops.object.modifier_apply(modifier=modifier.name)
    simplified_polygons = len(collision.data.polygons)

    bpy.ops.object.select_all(action="DESELECT")
    collision.select_set(True)
    floor.select_set(True)
    bpy.context.view_layer.objects.active = collision
    bpy.ops.object.join()
    collision.name = COLLISION_NAME
    collision.data.name = COLLISION_NAME
    collision.data.materials.clear()
    collision["ce_classname"] = "collider"
    collision["ce_collider"] = "triangle_mesh"
    collision["ce_physics_motion"] = "Static"
    collision["ce_collision_layer"] = 0
    collision["ce_enabled"] = True
    collision.display_type = "WIRE"
    collision.show_in_front = True
    collision.hide_render = True

    spawn.location = (0.0, 0.0, 0.0)
    bpy.ops.wm.save_as_mainfile(filepath=bpy.data.filepath)
    source_path = Path(bpy.data.filepath)
    physics = write_physics_asset(
        source_path,
        ROOT / "assets" / "compiled",
        collision,
        asset_path=lambda output: asset_path_for_project(ROOT, output),
        source_hash=source_fingerprint(source_path),
    )
    print(
        "Authored Sponza collision: "
        f"{simplified_polygons} simplified structure polygons + "
        f"{len(collision.data.polygons) - simplified_polygons} floor polygons "
        f"= {len(collision.data.polygons)} total; "
        f"cooked {physics.output}")


if __name__ == "__main__":
    main()
